### PR TITLE
fix: create and store label when colon is pressed

### LINKED ISSUE #2692: Alert labels are not stored
## Bug description

When creating a new alert, labels are not stored.

For example, creating an alert with label abc: xyz

image

When alert is saved, there are no labels for the alert:

image

## Expected behavior

Labels should be saved.

## Version information 
* **Signoz version**: v0.18.3
* **Browser version**: Chrome 113.0.5672.92 
* **Your OS and version**: MacOS Ventura 13.1
* **Your CPU Architecture**(ARM/Intel): Intel

### PR DESCRIPTION
**Pull request by Damans227**
Fixes #2692

When creating an Alert, the key value pair (label) field allows the user to include a colon in either key or value. It can cause confusion and lead users to believe the key and value must be included as one string in order to account for a label. This is exactly what caused #2692.

I would recommend that in addition to using `ENTER` as a way to end a key or value string, we also allow `COLON (:)` to do the same. In this way, the user will have a better experience. [This screen recording](https://www.loom.com/share/4eaa4272413d44f1813ad1c98e3be44e) shows how it works.

### CODE REVIEW

File: frontend/src/container/FormAlertRules/labels/index.tsx [hunk 1]
```diff
@@ -84,8 +84,9 @@ function LabelSelect({
 		handleBlur();
 	}, [handleBlur]);
 
-	const handleChange = (e: ChangeEvent<HTMLInputElement>): void => {
-		setCurrentVal(e.target?.value);
+	const handleLabelChange = (e: ChangeEvent<HTMLInputElement>): void => {
+		const processedCurrentVal = replace(e.target?.value, ':', '');
```
Comment (palashgdev) [inline frontend/src/container/FormAlertRules/labels/index.tsx:88]: can we use native replace

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Comment by palashgdev** [comment]
Hi @Damans227 
Thanks for raising the PR can you please the small suggestion though we in process to remove [lodash](https://github.com/SigNoz/signoz/issues/2032)

File: frontend/src/container/FormAlertRules/labels/index.tsx (hunk 1 above)
Comment (Damans227) [reply frontend/src/container/FormAlertRules/labels/index.tsx]: Sure. That sounds good.

**Review by palashgdev — APPROVED** [review]
