### PR TITLE
fix: return not-found error with diagnostic info for absent metrics

### LINKED ISSUE #10559: If a histogram metric hasn't seen data in a while, it gives a "something went wrong" error
This happens because the query that fetches for the metric type only checks the query's time range, and if no type is found, the statement builder does not change the space aggregation to sum, which leads to a p75(per_series_value) aggregation that leads to the something went wrong error

### PR DESCRIPTION
**Pull request by namanv3**
## Pull Request

---

### 📄 Summary
If a metric is not returned from the time series table with a temporality and type, that means it is not present with any data in the given time range, and hence we should skip it.

Screenshot 2026-03-12 at 14 14 21

Screenshot 2026-03-12 at 14 14 53

Screenshot 2026-03-12 at 14 16 56

Screenshot 2026-03-12 at 14 18 26

#### Issues closed by this PR
Closes #10559 
Closes https://github.com/SigNoz/engineering-pod/issues/4189

---

### ✅ Change Type
_Select all that apply_

- [ ] ✨ Feature
- [ ] 🐛 Bug fix
- [ ] ♻️ Refactor
- [ ] 🛠️ Infra / Tooling
- [ ] 🧪 Test-only

---

### 🐛 Bug Context
If a histogram metric hasn't seen data in a while, it gives a "something went wrong" error.

This happens because the query that fetches for the metric type only checks the query's time range, and if no type is found, the statement builder does not change the space aggregation to sum, which leads to a p75(per_series_value) aggregation that leads to the something went wrong error.

---

- Tests added/updated:
- Manual verification:
- Edge cases covered:

---

- Blast radius:
- Potential regressions:
- Rollback plan:

---

| Field | Value |
|------|-------|
| Deployment Type | Cloud / OSS / Enterprise |
| Change Type | Feature / Bug Fix / Maintenance |
| Description | User-facing summary |

---

### 📋 Checklist
- [ ] Tests added or explicitly not required
- [ ] Manually tested
- [ ] Breaking changes documented
- [ ] Backward compatibility considered

---

## 👀 Notes for Reviewers

---

### CODE REVIEW

File: pkg/querier/querier.go [hunk 1]
```diff
@@ -382,7 +382,7 @@ func (q *querier) QueryRange(ctx context.Context, orgID valuer.UUID, req *qbtype
 					}
 					// TODO(srikanthccv): warn when the metric is missing
 					if spec.Aggregations[i].Temporality == metrictypes.Unknown {
-						spec.Aggregations[i].Temporality = metrictypes.Unspecified
+						spec.Aggregations[i].Temporality = metrictypes.Unspecified // is this needed?
```
Comment (srikanthccv) [inline pkg/querier/querier.go]: I don't think it's relevant anymore given we now handle the multiple temporality.

File: pkg/telemetrymetrics/statement_builder.go [hunk 2]
```diff
@@ -299,6 +299,7 @@ func (b *MetricQueryStatementBuilder) buildTimeSeriesCTE(
 		sb.LTE("unix_milli", end),
 	)
 
+	// is this needed?
```
Comment (srikanthccv) [inline pkg/telemetrymetrics/statement_builder.go]: What do we do if a metric goes from `Cumulative` + Monotonic to `Gauge`?

File: pkg/telemetrymetadata/metadata.go [hunk 3]
```diff
@@ -1774,16 +1772,23 @@ func (t *telemetryMetaStore) fetchMetricsTemporalityAndType(ctx context.Context,
...
-		if err := rows.Scan(&metricName, &temporality, &metricType, &isMonotonic); err != nil {
+		var lastSeenAt int64
+		var firstSeenAt int64
+		if err := rows.Scan(&metricName, &temporality, &metricType, &isMonotonic, &lastSeenAt, &firstSeenAt); err != nil {
 			return nil, nil, errors.Wrapf(err, errors.TypeInternal, errors.CodeInternal, "failed to scan temporality result")
 		}
-		if temporality != metrictypes.Unknown {
-			temporalities[metricName] = append(temporalities[metricName], temporality)
-		}
+		// always pick the metric type, regardless of when it was seen
```
Comment (srikanthccv) [inline pkg/telemetrymetadata/metadata.go]: What's the behaviour if the metric is completely missing in the range?

Comment (namanv3) [reply pkg/telemetrymetadata/metadata.go]: the query above has no time range check whatsoever, so we're actually checking the full table. If it doesn't come up even then, then the metric just doesn't exist.

the fact that this change queries the whole table is my biggest concern over here

File: pkg/telemetrymetrics/statement_builder.go (hunk 2 above)
Comment (namanv3) [reply pkg/telemetrymetrics/statement_builder.go]: (I'm guessing this comment is for the other file)
Currently the only check is on histogram, if we need a check on counter/gauge then we need to change the above query. This we'd discussed when this change was first made as well

File: pkg/telemetrymetadata/metadata.go (hunk 3 above)
Comment (srikanthccv) [reply pkg/telemetrymetadata/metadata.go]: https://github.com/SigNoz/signoz/pull/10560#discussion_r2917619831

Here there is a TODO left to warn the users right away about the missing metric rather than attempt to query. We shouldn't let the code reach the point of the query preparation if we know that metric is missing in give period?

Comment (namanv3) [reply pkg/telemetrymetadata/metadata.go]: yes that also makes sense. Let me do this instead

Comment (namanv3) [reply pkg/telemetrymetadata/metadata.go]: this is done

**Comment by srikanthccv** [comment]
Reject the request with invalid input saying metric doesn't exist. It doesn't make sense to silently skip them without notifying user.

**Comment by namanv3** [comment]
@srikanthccv the metric may exist though, just that it has not seen any data recently. And this PR doesn't silently skip, it returns an empty response for that metric, which is the correct response.
The customer had an alert rule for a metric that isn't sending data anymore, wouldn't it make more sense for that customer to see no data instead of seeing an error?

**Comment by srikanthccv** [comment]
Empty response masks the underlying problem. The telemetry drift is a real problem and we deliberately take steps to show such issues to the user as early as possible otherwise it leads to dead alerts/dashboards (or any other assets) that are only discovered later when something goes bad. So the right choice is to let them know details, and about the _metric may exist_, there error should include the detail when did we see last and first see the metric, any other such diagnosis information.

See example https://github.com/SigNoz/signoz/issues/9523#issuecomment-3743836913

**Comment by namanv3** [comment]
@srikanthccv wanted to confirm this approach before adding the diagnostic information about the metric. 
One concern I see is that alerts will still silently fail with this change. Is that something to be handled in #9276 and not this PR?

**Comment by srikanthccv** [comment]
Yes, dead alerts is an independent problem.

**Comment by namanv3** [comment]
@srikanthccv added last seen info for missing metrics

File: pkg/types/telemetrytypes/store.go
Comment (srikanthccv) [inline pkg/types/telemetrytypes/store.go:1]: We will combine some of the functions into one function to fetch, type, temporality, first seen, last seen, etc... At this point, it would be premature.

Comment (namanv3) [reply pkg/types/telemetrytypes/store.go:1]: Yes makes sense. I've fixed the test and added a new one. Please review, will send it over to Vikrant after your approval is there
