### PR TITLE
Fix: PromQL handle __all__ variables

### LINKED ISSUE #9601: Dynamic variable doesn't work with PromQL when `ALL` option is selected
## How to reproduce

1. Create a dynamic variable of type multi-select with `ALL` option enabled
2. Use it in an promql expression, example (`sum(rate({"system.cpu.time", "host.name"=~"$host.name"}[5m]))`) where `host.name` is the variable name
3. Verify if it works with selecting one host
4. Verify if it works with selecting two hosts
5. Verify if it works with selecting `ALL` for variable

### PR DESCRIPTION
**Pull request by nikhilmantri0902**
## 📄 Summary
Closes #9601 

---

## ✅ Changes

- [ ] Feature: Brief description
- [ ] Bug fix: Brief description

---

## 🏷️ Required: Add Relevant Labels

> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one or more labels (as applicable):

ex:

- `frontend`
- `backend`
- `devops`
- `bug`
- `enhancement`
- `ui`
- `test`

---

## 👥 Reviewers

> Tag the relevant teams for review:

- frontend / backend / devops

---

## 🧪 How to Test

1. ...
2. ...
3. ...

---

## 🔍 Related Issues

Closes #

---

## 📸 Screenshots / Screen Recording (if applicable / mandatory for UI related changes)

---

## 📋 Checklist

- [ ] Dev Review
- [ ] Test cases added (Unit/ Integration / E2E)
- [ ] Manually tested the changes

---

### CODE REVIEW

File: pkg/querier/promql_query.go [hunk 1]
```diff
@@ -59,8 +60,52 @@ func (q *promqlQuery) Window() (uint64, uint64) {
...
+		return query, nil
+	}
+
+	// TODO(nikhilmantri0902, srikanthccv): should we return error if we fail to parse the query?
+	// or allow it for further processing?
+	// Parse the query into an AST
+	expr, err := parser.ParseExpr(query)
+	if err != nil {
+		return "", errors.WrapInternalf(err, errors.CodeInternal, "failed to parse PromQL query for __all__ removal")
+	}
```
Comment (srikanthccv) [inline pkg/querier/promql_query.go]: This wouldn't be appropriate error type. Right now, if the query input by user is invalid, we throw invalid error and say "invalid promql query ...". With this change, it will be internal which won't be right error type. Please check when does the `ParseExpr` return error?

File: pkg/querier/promql_query.go [hunk 2]
```diff
@@ -59,8 +60,52 @@ func (q *promqlQuery) Window() (uint64, uint64) {
...
+
+	// Create visitor and walk the AST
+	visitor := &allVarRemover{allVars: allVars}
+	if err := parser.Walk(visitor, expr, nil); err != nil {
```
Comment (srikanthccv) [inline pkg/querier/promql_query.go:89]: Same, when does the `Walk` return error and how should they be handled?

File: pkg/querier/promql_query_parser.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+// shouldRemoveMatcher checks if a matcher value contains a variable reference that has __all__ value.
+func (v *allVarRemover) shouldRemoveMatcher(value string) bool {
+	// Check for $var pattern
+	if strings.Contains(value, "$") {
+		for varName := range v.allVars {
+			if strings.Contains(value, "$"+varName) {
+				return true
+			}
+		}
+	}
```
Comment (srikanthccv) [inline pkg/querier/promql_query_parser.go:45]: `v.allVars` is already a map so do direct lookup instead of loop.

File: pkg/querier/promql_query.go (hunk 1 above)
Comment (nikhilmantri0902) [reply pkg/querier/promql_query.go]: if the promql expression is syntactically incorrect, it gives us error. Throwing an error with InvalidInput code now.

File: pkg/querier/promql_query.go (hunk 2 above)
Comment (nikhilmantri0902) [reply pkg/querier/promql_query.go:89]: It returns error if the Visit method returns an error. In our case, the visit method is not returning an error. How should this error then be handled?

File: pkg/querier/promql_query_parser.go (hunk 3 above)
Comment (nikhilmantri0902) [reply pkg/querier/promql_query_parser.go:45]: done

File: pkg/querier/promql_query.go (hunk 2 above)
Comment (srikanthccv) [reply pkg/querier/promql_query.go:89]: > It returns error if the Visit method returns an error. In our case, the visit method is not returning an error

That doesn't make sense.

Comment (nikhilmantri0902) [reply pkg/querier/promql_query.go:89]: As discussed logging this error and returning internal error.
