### PR TITLE
fix: escape and encode operations regex for overview details

### LINKED ISSUE #1485: Enpoint or opeations with conflicting promql special characters must be handled
## Bug description

If operation contains the wildcard matching character used by promql such as * exists it fails to parse. This failed if the API endpoint was something like `/**`.

## Expected behavior

It should still work and escape such character.

## How to reproduce

1. Create an operation which contains the double asterisk

## Version information 
* **Signoz version**: `0.10.1`

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes #1485

If an operation contains a character from regex special character set it needs to be escaped. For instance an operation named `/**` and `/\/\/\&$%$%2#2#%^56` will be changed to `/\*\*` and `/\\/\\/\\&\$%\$%2#2#%\^56`. But this alone doesn't fix the issue and throws an error unknown escaping sequence because the \ backslash is interpreted in the string literal not by the regex parser. This needs to escaped again or the input should be raw string. Double escaping will produce `/\\*\\*` and `/\\\/\\\/\\\&\\$%\\$%2#2#%\\^56` which also throws an unknown sequence which is strange. So instead of double escaping we are passing the raw string from the query using the backticks.

https://github.com/grafana/grafana/blob/f2ce8f266b9351ec7377d33d2b81e82e402e2024/public/app/features/templating/templateValuesSrv.js#L243-L245

https://go.dev/ref/spec#String_literals

https://stackoverflow.com/questions/6770898/unknown-escape-sequence-error-in-go

### CODE REVIEW

File: frontend/src/container/MetricsApplication/Tabs/Overview.tsx [hunk 1]
```diff
@@ -29,7 +30,15 @@ function Application({ getWidget }: DashboardProps): JSX.Element {
 		resourceAttributeQueries,
 		topLevelOperations,
 	} = useSelector<AppState, MetricReducer>((state) => state.metrics);
-	const operationsRegex = topLevelOperations.join('|');
+	const operationsRegex = useMemo(() => {
+		return encodeURIComponent(
+			topLevelOperations
+				.map((e) => {
+					return escapeRegExp(e);
```
Comment (palashgdev) [inline frontend/src/container/MetricsApplication/Tabs/Overview.tsx:37]: can we use implicit return here

**Review by palashgdev — APPROVED** [review]
LGTM

File: frontend/src/container/MetricsApplication/Tabs/Overview.tsx (hunk 1 above)
Comment (srikanthccv) [reply frontend/src/container/MetricsApplication/Tabs/Overview.tsx:37]: Sure

**Review by ankitnayan — APPROVED** [review]
