### PR TITLE
Fix/2967

### LINKED ISSUE #2967: Unable to see full name of attributes/tag in query builder
While adding any `group by` on attributes if attribute name is long then user can't full name, user needs to hover for 5-10s to see full name
Screenshot 2023-06-23 at 16 33 05

### PR DESCRIPTION
**Pull request by grvv**
closes #2967 

- Removes native browser title ( because it was slow and difficult to style )
- Showing users a tooltip only when the attribute name is a really long text.
Screenshot 2023-11-27 at 2 44 03 AM

### CODE REVIEW

File: frontend/src/container/TriggeredAlerts/Filter.tsx [hunk 1]
```diff
@@ -51,6 +75,7 @@ function Filter({
 
 	const options = uniqueLabels.map((e) => ({
 		value: e,
+		title: '',
```
Comment (grvv) [inline frontend/src/container/TriggeredAlerts/Filter.tsx:78]: To stop the default title from showing up. ( antd uses rc-select under the hood )
https://github.com/react-component/select/blob/ec0c6c748a24aa500ede15f1d2aacd0dacf4f63b/src/OptionList.tsx#L345

File: frontend/src/container/TriggeredAlerts/Filter.tsx [hunk 2]
```diff
@@ -1,11 +1,35 @@
...
-import { Tag } from 'antd';
-import { Dispatch, SetStateAction, useCallback, useMemo } from 'react';
+import { Tag, Tooltip } from 'antd';
+import { BaseOptionType } from 'antd/es/select';
+import { Dispatch, SetStateAction, useCallback, useMemo, useRef } from 'react';
 import { Alerts } from 'types/api/alerts/getTriggered';
 
 import { Container, Select } from './styles';
 
+function TextOverflowTooltip({
```
Comment (grvv) [inline frontend/src/container/TriggeredAlerts/Filter.tsx:10]: Because this component is only being used here, so I kept it here.

**Review by palashgdev — APPROVED** [review]

**Comment by palashgdev** [comment]
@YounixM please have a look and merge above PR

**Comment by srikanthccv** [comment]
@palashgdev please change the title to what the PR does before you merge PRs like this. Nobody knows what a _Fix/2967_ means. This goes into release notes.

**Comment by palashgdev** [comment]
> @palashgdev please change the title to what the PR does before you merge PRs like this. Nobody knows what a _Fix/2967_ means. This goes into release notes.

make sense updated 👍
