### PR TITLE
chore: alerts fixes and improvements

### LINKED ISSUE #391: For new alert channel page, webhook URL field should be made mandatory is slack is chosen as the alert channel
For slack to work as a notification channel, a webhook URL is necessary. Users should not be able to save the alert channel without providing webhook URL.

Users should be prompted to enter webhook URL if they try to save a new alert channel without providing webhook URL
Image 22-11-2021 at 12 27

### LINKED ISSUE #3961: [FE] Tags are inconsistent in triggered alerts when groupby filter is used
Hi SigNoz team, 

I came across FE issues, as described in the video, when the groupby filter is used in the triggered alerts section. I think tags can be given the same magenta colour when a table is expanded after a groupby filter is used. Also, if the tags' value is lengthy it overflows and distorts the table. 

Can someone from the team confirm whether these issues need to be fixed and shall I take it up? 

https://github.com/SigNoz/signoz/assets/64725924/23935d2b-1d99-4b36-a43b-c21c14daf98a

### LINKED ISSUE #6614: 3 front-end bugs
## bug1：New alarm channel has no form verification
When adding an alarm channel, the alarm channel name, web address, and email are not verified in the form, resulting in an interface error.
Image

## bug2：After searching for a card in the dashboard, clicking the Clear button does not execute the search again
Image

## bug3：The useAlertHistoryQueryParams hooks is not accurate in judging whether relativeTime is null
If the address is `http://localhost:3301/alerts/history?ruleId=1&relativeTime=null`, the relativeTime obtained by `params.get(QueryParams.relativeTime)` is a string of `'null'` instead of `null`, so the statement after `??` will not be executed
Image

Fix：
Image

## Version information 
* **Signoz version**: 0.5.7
* **Browser version**: Chrome 127.0.6533.89
* **Your OS and version**: Windows 10
* **Your CPU Architecture**(ARM/Intel):  Intel(R) Core(TM) i5-10600

### PR DESCRIPTION
**Pull request by amlannandy**
## 📄 Summary

- Fix the width of columns in triggered alerts table
- Add form validation on create alert channel form

---

## ✅ Changes

- [ ] Feature: Brief description
- [ ] Bug fix: Brief description

---

## 🏷️ Required: Add Relevant Labels

> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one or more labels (as applicable):

ex:

- `frontend`
- `backend`
- `devops`
- `bug`
- `enhancement`
- `ui`
- `test`

---

## 👥 Reviewers

> Tag the relevant teams for review:

- frontend / backend / devops

---

## 🧪 How to Test

1. ...
2. ...
3. ...

---

## 🔍 Related Issues

Closes #6614
Closes #1241 (in Eng pod)
Closes #391
Closes #3961

---

## 📸 Screenshots / Screen Recording (if applicable / mandatory for UI related changes)

---

## 📋 Checklist

- [ ] Dev Review
- [ ] Test cases added (Unit/ Integration / E2E)
- [ ] Manually tested the changes

---

## 👀 Notes for Reviewers

----

> [!IMPORTANT]
> Fix column width in triggered alerts table and add form validation for alert channel creation.
> 
>   - **UI Improvements**:
>     - Set `minWidth` to `90px` for `TableCell` in `ExapandableRow.tsx`, `TableRow.tsx`, and `index.tsx` to fix column width in triggered alerts table.
>   - **Form Validation**:
>     - Add validation for `api_url`, `api_key`, `to`, and `name` fields in `CreateAlertChannels/index.tsx`.
>     - Update error messages in `channels.json` for missing required fields.
>   - **Tests**:
>     - Update `CreateAlertChannel.test.tsx` to check for error notifications when required fields are missing.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for 3b51ce88a484b72b98068446b0c15ae6de6e87d5. You can [customize](https://app.ellipsis.dev/SigNoz/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: frontend/src/container/CreateAlertChannels/index.tsx [hunk 1]
```diff
@@ -138,6 +138,15 @@ function CreateAlertChannels({
 	);
 
 	const onSlackHandler = useCallback(async () => {
+		if (!selectedConfig.api_url) {
+			console.log('selectedConfig', selectedConfig);
```
Comment (SagarRajput-7) [inline frontend/src/container/CreateAlertChannels/index.tsx]: remove console.log

**Review by SagarRajput-7 — APPROVED** [review]
