### PR TITLE
Fixed svg color mismatch in light mode and dark mode

### LINKED ISSUE #492: svg fill color mismatch
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Light Mode
Screenshot 2021-12-10 at 8 15 55 PM

Dark Mode
Screenshot 2021-12-10 at 8 17 41 PM

## Expected behavior
in light mode, dark mode both should be visible and both should have same color

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
Fixes #492 

Steps to fix:-
1). got the isDarkMode state from the store
2). used ternary operator in fill of SVG to set fill according to theme

SS to indicate the changes:-

image

image

### CODE REVIEW

**Review by Devesh21700Kumar — COMMENTED** [review]
@pal-sig  @ankitnayan do check this out

File: frontend/src/assets/Dashboard/Value.tsx [hunk 1]
```diff
@@ -1,6 +1,12 @@
 import React from 'react';
+import { useSelector } from 'react-redux';
+import { AppState } from 'store/reducers';
+import AppReducer from 'types/reducer/app';
 
-const Value = (): JSX.Element => (
+const Value = (): JSX.Element => {
+	const { isDarkMode } = useSelector<AppState, AppReducer>((state) => state.app);
```
Comment (pal-sig) [inline frontend/src/assets/Dashboard/Value.tsx:7]: can we pass color as props here

**Review by pal-sig — CHANGES_REQUESTED** [review]

File: frontend/src/assets/Dashboard/Value.tsx (hunk 1 above)
Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx:7]: Since the parent component was not using isDarkMode variable I thought it would be better to just import it from the store.

But if you are talking about the color `black` which has been added separately then I think it can be done.
So I think I can pass it as props from this parent  
https://github.com/SigNoz/signoz/blob/main/frontend/src/container/NewDashboard/ComponentsSlider/index.tsx

Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx:7]: @pal-sig shall i make that change or is the present one ok?

Comment (pal-sig) [reply frontend/src/assets/Dashboard/Value.tsx:7]: @Devesh21700Kumar just make Value Icon function which will accept fillColor

Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx:7]: So do you want me to do this?

fill=fillColor()}

	const fillColor = () => {
		const color = isDarkMode?"white" : "balck";
		return color;
	 }
	 
	 and then use fillColor function in fill ?

Comment (pal-sig) [reply frontend/src/assets/Dashboard/Value.tsx:7]: no @Devesh21700Kumar just pass the color as prop and do all the calculation in the parent

Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx]: @pal-sig added color as a prop on its parent and exported the whole as a TSX file.

Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx]: @pal-sig  changed this

File: frontend/src/assets/Dashboard/TimeSeries.tsx [hunk 2]
```diff
@@ -1,35 +1,41 @@
...
-			<pattern
-				id="pattern0"
-				patternContentUnits="objectBoundingBox"
-				width="1"
-				height="1"
-			>
-				<use
-					xlinkHref="#image0"
-					transform="translate(0 -0.0365149) scale(0.015625 0.0275136)"
+const TimeSeries = (props: colorProps): JSX.Element => (
```
Comment (pal-sig) [inline frontend/src/assets/Dashboard/TimeSeries.tsx:3]: can we change colorProps into `TimeSeriesProps` ?

File: frontend/src/assets/Dashboard/Value.tsx [hunk 3]
```diff
@@ -1,18 +1,25 @@
...
-			fill="white"
-		/>
-	</svg>
-);
+const Value = (props: colorProps): JSX.Element => {
```
Comment (pal-sig) [inline frontend/src/assets/Dashboard/Value.tsx:3]: can we change colorProps into `ValueProps` ?

File: frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts [hunk 4]
```diff
@@ -18,8 +18,11 @@ export type ITEMS = 'TIME_SERIES' | 'VALUE';
 
 interface ItemsProps {
 	name: ITEMS;
-	Icon: () => JSX.Element;
+	Icon: (props: colorProps) => JSX.Element;
 	display: string;
 }
 
+interface colorProps{
```
Comment (pal-sig) [inline frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts:25]: feel like this is repetitive 

can we import from icon and use here ?

**Review by pal-sig — CHANGES_REQUESTED** [review]

File: frontend/src/assets/Dashboard/TimeSeries.tsx (hunk 2 above)
Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/TimeSeries.tsx:3]: sure

File: frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts (hunk 4 above)
Comment (Devesh21700Kumar) [reply frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts:25]: ok

File: frontend/src/assets/Dashboard/Value.tsx (hunk 3 above)
Comment (Devesh21700Kumar) [reply frontend/src/assets/Dashboard/Value.tsx:3]: sure

**Comment by Devesh21700Kumar** [comment]
@pal-sig  made the changes

**Review by pal-sig — APPROVED** [review]
