### PR TITLE
fix(FE): encode URL query params

### LINKED ISSUE #3493: Fix code scanning alert - Client-side cross-site scripting
Tracking issue for:
- [ ] https://github.com/SigNoz/signoz/security/code-scanning/108

### LINKED ISSUE #3494: Fix code scanning alert - Client-side cross-site scripting
Tracking issue for:
- [ ] https://github.com/SigNoz/signoz/security/code-scanning/106

### LINKED ISSUE #3495: Fix code scanning alert - Client-side cross-site scripting
Tracking issue for:
- [ ] https://github.com/SigNoz/signoz/security/code-scanning/104

### LINKED ISSUE #3496: Fix code scanning alert - Client-side cross-site scripting
Tracking issue for:
- [ ] https://github.com/SigNoz/signoz/security/code-scanning/101

### PR DESCRIPTION
**Pull request by CKanishka**
Fixes #3493 
Fixes #3494 
Fixes #3495 
Fixes #3496

### CODE REVIEW

**Review by palashgdev — APPROVED** [review]

File: frontend/src/lib/createQueryParams.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 const createQueryParams = (params: { [x: string]: string | number }): string =>
 	Object.keys(params)
-		.map((k) => `${k}=${encodeURI(String(params[k]))}`)
+		.map(
+			(k) => `${encodeURIComponent(k)}=${encodeURIComponent(String(params[k]))}`,
```
Comment (palashgdev) [inline frontend/src/lib/createQueryParams.ts:4]: we don't need to encode the key

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Review by palashgdev — APPROVED** [review]
