### PR TITLE
chore: added tooltip events + minor ui fixes

### LINKED ISSUE #11087: Add tooltip analytics events + minor UI fixes
Image

### PR DESCRIPTION
**Pull request by ahrefabhi**
## Pull Request

---

### 📄 Summary

Adds analytics event tracking for tooltip interactions (pin, unpin, content scroll) on uPlot charts, and ships a set of minor UI polish fixes to the tooltip footer and item components.

**Events added:**
- `TOOLTIP_PINNED` — fired when a user pins the tooltip (click on chart)
- `TOOLTIP_UNPINNED` — fired when a user clicks the unpin button
- `TOOLTIP_CONTENT_SCROLLED` — fired once the first time a user scrolls the tooltip list

**UI fixes:**
- TooltipFooter: redesigned the un-pinned hint area to show two hints (click to drilldown + press key to pin), using a `MousePointerClick` icon; border-top changed from solid to dashed; background uses `l1` instead of `l2`
- TooltipItem: removed hover highlight styles (`cursor: pointer`, background, opacity override) — items are no longer interactive-looking when the tooltip is not pinned
- ChartWrapper: increased `TOOLTIP_MIN_WIDTH` from 200 → 300px for better readability
- `@ts-ignore` → `@ts-expect-error` and cleaned up a double-cast type assertion in `TooltipPlugin`

#### Screenshots / Screen Recordings (if applicable)

Before
image

After
image

image

#### Issues closed by this PR
Closes #11087

---

### ✅ Change Type
_Select all that apply_

- [ ] ✨ Feature
- [x] 🐛 Bug fix
- [x] ♻️ Refactor
- [ ] 🛠️ Infra / Tooling
- [ ] 🧪 Test-only

---

#### Root Cause
Tooltip items showed hover highlight styles (pointer cursor, background, opacity) even when the tooltip was not in a pinned/interactive state, giving users a misleading affordance that items were clickable when they were not.

#### Fix Strategy
Removed the hover CSS rules from `TooltipItem` so items only appear interactive when the tooltip is actually pinned and drilldown is available.

---

### 🧪 Testing Strategy

- Tests added/updated: Not required — changes are purely presentational UI adjustments and analytics event wiring
- Manual verification: Verified tooltip pin/unpin behavior, footer hint display in both pinned and un-pinned states, and that events fire correctly
- Edge cases covered: Scroll event fires only once per tooltip open (guarded by `isScrollEventTriggered` ref)

---

### ⚠️ Risk & Impact Assessment

- Blast radius: Tooltip UI in all uPlot v2 charts (dashboards, metrics explorer, etc.)
- Potential regressions: Tooltip item hover appearance change is intentional but visible — items no longer show a background on hover
- Rollback plan: Revert this commit; no data migrations or API changes involved

---

### 📝 Changelog

| Field | Value |
|------|-------|
| Deployment Type | Cloud / OSS / Enterprise |
| Change Type | Maintenance |
| Description | Tooltip footer UI polish and analytics event tracking for pin/unpin/scroll interactions |

---

### 📋 Checklist
- [x] Tests added or explicitly not required
- [x] Manually tested
- [ ] Breaking changes documented
- [x] Backward compatibility considered

---

## 👀 Notes for Reviewers

- The `TOOLTIP_CONTENT_SCROLLED` event is fire-once per tooltip mount (guarded by a `useRef` flag), so it won't spam analytics on every scroll tick.
- The footer hint redesign only affects the un-pinned state — the pinned state footer (press key/Esc to unpin + dismiss button) is unchanged.
- `@ts-ignore` → `@ts-expect-error` is a minor TypeScript hygiene fix with no runtime effect.

---

### CODE REVIEW

File: frontend/src/lib/uPlotV2/components/Tooltip/components/TooltipList/TooltipList.tsx [hunk 1]
```diff
@@ -33,11 +36,21 @@ export default function TooltipList({
 		[totalListHeight, content.length],
 	);
 
+	const handleScroll = useCallback(() => {
+		if (!isScrollEventTriggered.current) {
+			logEvent(Events.TOOLTIP_CONTENT_SCROLLED, {
+				path: window.location.pathname,
```
Comment (AshwinBhatkal) [inline frontend/src/lib/uPlotV2/components/Tooltip/components/TooltipList/TooltipList.tsx]: use the new path url function here

Comment (AshwinBhatkal) [reply frontend/src/lib/uPlotV2/components/Tooltip/components/TooltipList/TooltipList.tsx]: add a TODO to clear event after 3 months

File: frontend/src/lib/uPlotV2/plugins/TooltipPlugin/TooltipPlugin.tsx [hunk 2]
```diff
@@ -328,16 +330,19 @@ export default function TooltipPlugin({
...
 				target: plot.over,
 				offsetX: cursorLeft,
 				offsetY: cursorTop,
-			} as unknown) as MouseEvent;
+			} as unknown as MouseEvent;
 
 			controller.clickData = buildClickData(syntheticEvent, plot);
 			controller.pinned = true;
+			logEvent(Events.TOOLTIP_PINNED, {
+				path: window.location.pathname,
```
Comment (AshwinBhatkal) [inline frontend/src/lib/uPlotV2/plugins/TooltipPlugin/TooltipPlugin.tsx]: use new function here as well

File: frontend/src/lib/uPlotV2/components/Tooltip/components/TooltipFooter/TooltipFooter.tsx [hunk 3]
```diff
@@ -16,27 +19,41 @@ export default function TooltipFooter({
 	isPinned,
 	dismiss,
 }: TooltipFooterProps): JSX.Element {
+	const handleUnpinClick = (): void => {
+		logEvent(Events.TOOLTIP_UNPINNED, {
+			path: window.location.pathname,
```
Comment (AshwinBhatkal) [inline frontend/src/lib/uPlotV2/components/Tooltip/components/TooltipFooter/TooltipFooter.tsx]: new url function

**Review by AshwinBhatkal — DISMISSED** [review]

**Review by AshwinBhatkal — APPROVED** [review]
