### PR TITLE
fix: filters applied in the logs page

### LINKED ISSUE #2208: FE: filters applied in the logs page
when we share the logs url with filters it is reseting to empty string 

Steps To Reproduce:
1. when we interact with logs filter
1. share the url or open the url in new tab
1. selected filter is empty

https://www.loom.com/share/82297636262f48ae8aa523e71fd023f1

### PR DESCRIPTION
**Pull request by KolesnikAntony**
Close #2208

### CODE REVIEW

File: frontend/src/container/LogsSearchFilter/useSearchParser.ts [hunk 1]
```diff
@@ -27,11 +27,14 @@ export function useSearchParser(): {
 	const {
 		searchFilter: { parsedQuery, queryString },
 	} = useSelector<AppState, ILogsReducer>((store) => store.logs);
+
 	const { minTime, maxTime, selectedTime } = useSelector<
 		AppState,
 		GlobalReducer
 	>((store) => store.globalTime);
 
+	console.log(queryString, '-----query string');
```
Comment (palashgdev) [inline frontend/src/container/LogsSearchFilter/useSearchParser.ts:36]: console

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Review by palashgdev — CHANGES_REQUESTED** [review]
https://www.loom.com/share/c477438a41c745709ee60220b800c44a

**Review by palashgdev — CHANGES_REQUESTED** [review]
@KolesnikAntony i guess query is not parsed correctly

Screenshot 2023-02-10 at 8 20 29 PM

Screenshot 2023-02-10 at 8 20 37 PM

**Review by palashgdev — APPROVED** [review]
