### PR TITLE
fix: add missing data for promql and anomaly rules

### LINKED ISSUE #9146: PromQl | Anomaly Missing Sample | No data Alert support

### PR DESCRIPTION
**Pull request by jatinderjit**
## Pull Request

---

### 📄 Summary

Add support for missing data alerts for PromQL and Anomaly rules

Closes #9146

---

### ✅ Change Type

- [ ] ✨ Feature
- [x] 🐛 Bug fix
- [ ] ♻️ Refactor
- [ ] 🛠️ Infra / Tooling
- [ ] 🧪 Test-only

---

### 🐛 Bug Context

Alerts for missing data can currently be configured for threshold rules only.
This PR adds similar support for PromQL and Anomaly rules.

---

- Tests added/updated: added tests for promql rules
- Manual verification:
- Edge cases covered:

---

- Blast radius:
- Potential regressions:
- Rollback plan:

---

| Field | Value |
|------|-------|
| Deployment Type | Cloud / OSS / Enterprise |
| Change Type | Feature / Bug Fix / Maintenance |
| Description | User-facing summary |

---

### 📋 Checklist
- [x] Tests added or explicitly not required
- [ ] Manually tested
- [ ] Breaking changes documented
- [ ] Backward compatibility considered

---

## 👀 Notes for Reviewers

---

### CODE REVIEW

File: ee/query-service/rules/anomaly.go [hunk 1]
```diff
@@ -234,8 +235,32 @@ func (r *AnomalyRule) buildAndRunQuery(ctx context.Context, orgID valuer.UUID, t
...
+		lbls := labels.NewBuilder(labels.Labels{})
+		if !r.LastTimestampWithDatapoints().IsZero() {
+			lbls.Set(ruletypes.LabelLastSeen, r.LastTimestampWithDatapoints().Format(constants.AlertTimeFormat))
+		}
+		resultVector = append(resultVector, ruletypes.Sample{
+			Metric:    lbls.Labels(),
+			IsMissing: true,
+		})
+		return resultVector, nil
+	}
```
Comment (srikanthccv) [inline ee/query-service/rules/anomaly.go]: Since this is a feature that is shared b/w all rule types, should this be part of base rule?

**Review by srikanthccv — APPROVED** [review]
```
Running tool: /usr/local/go/bin/go test -test.fullpath=true -timeout 30s -run ^TestPromRule_NoData_AbsentFor$ github.com/SigNoz/signoz/pkg/query-service/rules

=== RUN   TestPromRule_NoData_AbsentFor
=== RUN   TestPromRule_NoData_AbsentFor/WithinGracePeriod
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:48:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:53:20 +0530 IST
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:52:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:53:20 +0530 IST
--- PASS: TestPromRule_NoData_AbsentFor/WithinGracePeriod (0.00s)
=== RUN   TestPromRule_NoData_AbsentFor/AfterGracePeriod
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:48:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:53:20 +0530 IST
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:54:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:53:20 +0530 IST
--- PASS: TestPromRule_NoData_AbsentFor/AfterGracePeriod (0.00s)
--- PASS: TestPromRule_NoData_AbsentFor (0.00s)
PASS
ok      github.com/SigNoz/signoz/pkg/query-service/rules        (cached)
```

```
=== RUN   TestPromRule_NoData_AbsentFor
=== RUN   TestPromRule_NoData_AbsentFor/WithinGracePeriod
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:48:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:50:20 +0530 IST
s.Interval 1m0s
lastTimestampWithDatapoints 2023-11-15 03:48:20 +0530 IST
r.ruleCondition.AlertOnAbsent true
ts 2023-11-15 03:52:20 +0530 IST
r.lastTimestampWithDatapoints.Add(time.Duration(r.ruleCondition.AbsentFor)*time.Minute) 2023-11-15 03:50:20 +0530 IST
    /Users/srikanth/work/signoz/pkg/query-service/rules/prom_rule_test.go:1612:
                Error Trace:    /Users/srikanth/work/signoz/pkg/query-service/rules/prom_rule_test.go:1612
                Error:          Not equal:
                                expected: 0
                                actual  : 1
                Test:           TestPromRule_NoData_AbsentFor/WithinGracePeriod
--- FAIL: TestPromRule_NoData_AbsentFor/WithinGracePeriod (0.00s)
```

Thank you!
