### PR TITLE
fix: it has been fixed of difficult to click on metrics graph points

### LINKED ISSUE #2194: Difficult to click on metrics graph points to view traces
With the recent introduction of drag to zoom on graphs, it has become challenging to click on graph points and results in unintended drags.
https://www.loom.com/share/24195660d8124864bcff0af2fd74dc16

### PR DESCRIPTION
**Pull request by KolesnikAntony**
Close #2194 
-it has been fixed of difficult to click on metrics graph points;
-DataSets of chart has been refactored and minimized;

### CODE REVIEW

File: frontend/src/container/MetricsApplication/Tabs/Overview.tsx [hunk 1]
```diff
@@ -77,6 +77,57 @@ function Application({ getWidgetQueryBuilder }: DashboardProps): JSX.Element {
 		[servicename, topLevelOperations, tagFilterItems, getWidgetQueryBuilder],
 	);
 
+	const onTracePopupClick = (timestamp: number): void => {
```
Comment (palashgdev) [inline frontend/src/container/MetricsApplication/Tabs/Overview.tsx:80]: @KolesnikAntony is this https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/MetricsApplication/Tabs/util.ts#L38 the same util ?

**Review by palashgdev — CHANGES_REQUESTED** [review]

File: frontend/src/container/MetricsApplication/Tabs/Overview.tsx (hunk 1 above)
Comment (KolesnikAntony) [reply frontend/src/container/MetricsApplication/Tabs/Overview.tsx:80]: Probably made mistake when was merging it. Will fix

File: frontend/src/container/MetricsApplication/Tabs/Overview.tsx [hunk 2]
```diff
@@ -102,6 +102,43 @@ function Application({ getWidgetQueryBuilder }: DashboardProps): JSX.Element {
...
 
+	const generalChartDataProperties = useCallback(
+		(title: string, colorIndex: number) => ({
+			borderColor: colors[colorIndex],
+			label: title,
+			showLine: true,
+			borderWidth: 1.5,
+			spanGaps: true,
+			pointRadius: 2,
+			pointHoverRadius: 8,
```
Comment (palashgdev) [inline frontend/src/container/MetricsApplication/Tabs/Overview.tsx:113]: pointHoverRadius with 8 it is looking weird

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Comment by palashgdev** [comment]
@KolesnikAntony can you please verify increasing or reducing the radius is not solving the issue

File: frontend/src/components/Graph/index.tsx [hunk 3]
```diff
@@ -374,4 +374,4 @@ Graph.defaultProps = {
 	onDragSelect: undefined,
 	dragSelectColor: undefined,
 };
-export default Graph;
+export default React.memo(Graph);
```
Comment (palashgdev) [inline frontend/src/components/Graph/index.tsx:377]: can you please revert this change ... already there is memo in develop branch can you please take the reference from there

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Comment by KolesnikAntony** [comment]
It has been added condition which gives us posibilities to compare start and end position of mouseDown and mouseUp. So as DND works on mouseDown and MouseUp events we were getting the reload of timestamps by click or double click.

**Comment by palashgdev** [comment]
> It has been added condition which gives us posibilities to compare start and end position of mouseDown and mouseUp. So as DND works on mouseDown and MouseUp events we were getting the reload of timestamps by click or double click.

ok this sounds good to me

**Review by palashgdev — APPROVED** [review]
