### PR TITLE
NOOP to Count in alert creation from logs

### LINKED ISSUE #5223: Remove the NOOP option in alerts query builder
## Bug description

The NOOP is not supported in alerts. We only support threshold-based alerts.

### PR DESCRIPTION
**Pull request by ahmadshaheer**
### Summary
NOOP to Count in alert creation from logs and traces

#### Related Issues / PR's
Part of #5223 

#### Screenshots
Before:
https://www.loom.com/share/b4204652c3924bd9aecd84585cfd4d3e

After:
https://www.loom.com/share/a2ff73e0307b4bee81fb84f153e0b9ca

### CODE REVIEW

File: frontend/src/pages/TracesExplorer/Filter/Filter.tsx [hunk 1]
```diff
@@ -184,6 +184,13 @@ export function Filter(props: FilterProps): JSX.Element {
 					...currentQuery.builder,
 					queryData: currentQuery.builder.queryData.map((item) => ({
 						...item,
+						// on creating alert from Traces page and coming back to Traces, the count aggregateOperator causes an error, therefore, changing it back to noop
```
Comment (srikanthccv) [inline frontend/src/pages/TracesExplorer/Filter/Filter.tsx:187]: @ahmadshaheer please help me understand why this hack is needed specifically in Traces Explorer and not in Logs Explorer.

Comment (ahmadshaheer) [reply frontend/src/pages/TracesExplorer/Filter/Filter.tsx:187]: @srikanthccv , on coming back to traces page after creating alert from it, The noop would get replaced with count which would cause an issue. 

I was facing this issue only on traces page (please refer to the loom videos). therefore, added this code.

I later discussed with @YounixM , and he suggested that we have to move the modification logic inside the `useGetCompositeQueryParam`. I tried implementing it there, but I wasn't able to get the `panel type` (we wanted the query modification to happen only for list view and traces). 

I will repick fixing this issue today/tomorrow and properly fix it. 

Video 1: [Traces -> create alert -> go back -> error](https://www.loom.com/share/1ad14534aab84410a519fadd34407edd)
Video 2: [Logs -> create alert -> go back -> works fine](https://www.loom.com/share/d2a88d63ca8f4f8caf1b1896abef02c8)

**Review by YounixM — APPROVED** [review]
