### PR TITLE
fix: adding missing flags to run go-run-community

### LINKED ISSUE #8623: make go-run-community fails with "unknown flag: --config"
## Bug description
When running `make go-run-community` the code does not execute. 
It throws the following error
```json
{
  "timestamp": "2025-07-27T13:06:47.97561+05:30",
  "level": "ERROR",
  "code": {
    "function": "github.com/SigNoz/signoz/cmd.Execute",
    "file": ".../signoz/cmd/root.go",
    "line": 30
  },
  "msg": "error running command",
  "error": "unknown flag: --config"
}
```

Image

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

Should start the server according to the below documentation:
https://github.com/SigNoz/signoz/blob/main/docs/contributing/development.md

## How to reproduce

1. Clone the repo
2. Follow the documentation https://github.com/SigNoz/signoz/blob/main/docs/contributing/development.md
3. Run `make go-run-community`

## Version information 
* **Signoz version**: main-65018abc4 (v0.91.0)
* **Browser version**:
* **Your OS and version**: MacOS 15.4.1 
* **Your CPU Architecture**(ARM/Intel): ARM

### PR DESCRIPTION
**Pull request by harshitrajsinha**
## 📄 Summary

The change adds missing flags required during execution of `make go-run-community`. Currently, running the command cause the error "unknown flag: --config", mentioned in the issue #8623 

---

## ✅ Changes

* Adds missing flags for config and cluster referenced in Makerfile required by root command.
* Adds server subcommand to Makerfile
---

## 👥 Reviewers

> Tag the relevant teams for review:

- backend
- @srikanthccv 
- @YounixM 

---

## 🧪 How to Test

1. make go-run-community
2. curl http://localhost:8080/api/v1/health

---

## Screenshot

Screenshot 2025-07-29 175332

---

## 🔍 Related Issues

Closes #8623

---

## 👀 Notes for Reviewers

* Current state on running `make go-run-community`
```bash
{"timestamp":"2025-07-29T11:50:13.306971609Z","level":"ERROR","code":{"function":"github.com/SigNoz/signoz/cmd.Execute","file":"/home/rajsinha/signoz/cmd/root.go","line":39},"msg":"error running command","error":"unknown flag: --config"}
exit status 1
make: *** [Makefile:87: go-run-community] Error 1
```

----

> [!IMPORTANT]
> Fixes missing flags in `Makefile` and `cmd/root.go` for `go-run-community` command execution.
> 
>   - **Makefile**:
>     - Adds `server` subcommand to `go-run-community` target to fix execution error.
>   - **cmd/root.go**:
>     - Adds `config` and `cluster` flags to `RootCmd` to support configuration and cluster name specification.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for e18093e4d6e9bfce43ff0e77f440ce1e2f034877. You can [customize](https://app.ellipsis.dev/SigNoz/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -18,6 +18,15 @@ var RootCmd = &cobra.Command{
 	CompletionOptions: cobra.CompletionOptions{DisableDefaultCmd: true},
 }
 
+// Add config flag
```
Comment (therealpandey) [inline cmd/root.go]: This has now been deprecated. Only the change in the Makefile should suffice.

**Review by grandwizard28 — CHANGES_REQUESTED** [review]

File: cmd/root.go (hunk 1 above)
Comment (harshitrajsinha) [reply cmd/root.go]: Indeed it works correctly with just change in Makerfile. Updated the PR by removing the changes from root.go

**Comment by therealpandey** [comment]
@harshitrajsinha please sign the CLA agreement.

**Comment by yash492** [comment]
Ahh, this is what I missed. Thanks @harshitrajsinha. I feel same changes are required for `make go-run-enterprise`

**Review by grandwizard28 — APPROVED** [review]
