### PR TITLE
fix: [GH-3790]: timerange not working for different users

### LINKED ISSUE #3790: FE: Timerange is not working on URL
## Bug description

I am trying to share logs from a specified timerange and filters.

Creating a filter by k8s_namespace_name and set the timerange in a custom timerange.

I copy the URL and change the timerange that should be this part  timeRange=%7B%22start%22%3A1698147394000%2C%22end%22%3A1698233796000%2C%22 
that means **start** 1698147394000 and **end** 1698233796000

This still happening when I use the share button
image

http://{URL}/logs-explorer?options=%7B%22selectColumns%22%3A%5B%5D%2C%22maxLines%22%3A2%2C%22format%22%3A%22list%22%7D&timeRange=%7B%22start%22%3A1698147394000%2C%22end%22%3A1698233796000%2C%22pageSize%22%3A100%7D&compositeQuery=%257B%2522queryType%2522%253A%2522builder%2522%252C%2522builder%2522%253A%257B%2522queryData%2522%253A%255B%257B%2522dataSource%2522%253A%2522logs%2522%252C%2522queryName%2522%253A%2522A%2522%252C%2522aggregateOperator%2522%253A%2522noop%2522%252C%2522aggregateAttribute%2522%253A%257B%2522id%2522%253A%2522------false%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522key%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522type%2522%253A%2522%2522%252C%2522isJSON%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522items%2522%253A%255B%255D%252C%2522op%2522%253A%2522AND%2522%257D%252C%2522expression%2522%253A%2522A%2522%252C%2522disabled%2522%253Afalse%252C%2522having%2522%253A%255B%255D%252C%2522stepInterval%2522%253A240%252C%2522limit%2522%253Anull%252C%2522orderBy%2522%253A%255B%257B%2522columnName%2522%253A%2522timestamp%2522%252C%2522order%2522%253A%2522desc%2522%257D%255D%252C%2522groupBy%2522%253A%255B%255D%252C%2522legend%2522%253A%2522%2522%252C%2522reduceTo%2522%253A%2522sum%2522%257D%255D%252C%2522queryFormulas%2522%253A%255B%255D%257D%252C%2522promql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522query%2522%253A%2522%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%257D%255D%252C%2522clickhouse_sql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%252C%2522query%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%25224cd6b481-fbf0-40ba-b869-9aa602b70462%2522%257D

But when I enter with another browser, I still see the las 15 mins (the default)
image

## Expected behavior

When share the link with the timerange setted. the logs that should be displayed, should be within that timerange

## How to reproduce

1. Go to Front end and log in
2. Filter logs by something (in this case by k8s_namespace_name) and put a custom timerange 
3. Copy the url or click on the share button.
4. Enter with that url, you will see the last 15 mins instead the custom timerange.

## Version information 
* **Signoz version**:
* FE: 0.32.0
* **Browser version**:
* Chrome Versión 118.0.5993.88 (Build oficial) (64 bits)
* **Your OS and version**:
* Ubuntu 22.04.3 LTS

## Additional context

I am trying to put SigNoz on a Kubernetes Cluster and record logs from Cluster that are deploying on CI/CD. 
And I need to create a link so that the devs can see the logs that SigNoz collects from that particular cluster.

### PR DESCRIPTION
**Pull request by Vikrant2520**
### Summary

- the startTime and endTime were not getting populated in the URL hence the sharing of timezones were not working for different users
- Now if one user selects some time range and opens it up in different tab OR shares it to a different user , they will see the time range exactly which was being used while sharing the URL

#### Related Issues / PR's

This resolves #3790

#### Screenshots

https://github.com/SigNoz/signoz/assets/54737045/6064b506-df9b-4023-91dc-5193d03b55f5

### CODE REVIEW

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx [hunk 1]
```diff
@@ -187,6 +190,11 @@ function DateTimeSelection({
 
 		const { maxTime, minTime } = GetMinMax(value, getTime());
 
+		urlQuery.set(QueryParams.startTime, minTime.toString());
+		urlQuery.set(QueryParams.endTime, maxTime.toString());
+		const generatedUrl = `${location.pathname}?${urlQuery.toString()}`;
+		history.replace(generatedUrl);
+
 		initQueryBuilderData(updateStepInterval(stagedQuery, maxTime, minTime));
```
Comment (palashgdev) [inline frontend/src/container/TopNav/DateTimeSelection/index.tsx:198]: `initQueryBuilderData` is also replacing the history can we optimise this one ?

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx [hunk 2]
```diff
@@ -207,6 +215,10 @@ function DateTimeSelection({
 				setLocalStorageKey('startTime', startTimeMoment.toString());
 				setLocalStorageKey('endTime', endTimeMoment.toString());
 				updateLocalStorageForRoutes('custom');
+				urlQuery.set(QueryParams.startTime, startTimeMoment.toString());
+				urlQuery.set(QueryParams.endTime, endTimeMoment.toString());
+				const generatedUrl = `${location.pathname}?${urlQuery.toString()}`;
```
Comment (palashgdev) [inline frontend/src/container/TopNav/DateTimeSelection/index.tsx:220]: can we use createQueryParams directly rather than adding directly

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx (hunk 1 above)
Comment (Vikrant2520) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx:198]: let me check this in follow up PR

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx (hunk 2 above)
Comment (Vikrant2520) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx]: done

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx (hunk 1 above)
Comment (palashgdev) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx:202]: if you are working an issue which is intermediately fixed create a sub task which is not closing the issue otherwise we will lose the track

Comment (Vikrant2520) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx:202]: Yes we have one other issue mentioned in the same ticket so will resolve with the same

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx [hunk 3]
```diff
@@ -169,6 +173,11 @@ function DateTimeSelection({
 		return `Last refresh - ${secondsDiff} sec ago`;
 	}, [maxTime, minTime, selectedTime]);
 
+	const isLogsExplorerPage = useMemo(
```
Comment (palashgdev) [inline frontend/src/container/TopNav/DateTimeSelection/index.tsx:176]: marking an explicit approval but need to fix the root cause

**Review by palashgdev — DISMISSED** [review]

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx (hunk 3 above)
Comment (Vikrant2520) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx:176]: https://github.com/SigNoz/signoz/issues/4233 Will investigate here

**Review by YounixM — APPROVED** [review]

File: frontend/src/container/TopNav/DateTimeSelection/index.tsx (hunk 3 above)
Comment (Vikrant2520) [reply frontend/src/container/TopNav/DateTimeSelection/index.tsx:176]: Resolving the comment
