### PR TITLE
Fix: Different time formats in hover legend and x-axis on charts

### LINKED ISSUE #892: Different time formats in hover legend and x-axis on charts
The time stamp in the hover legend is in the 12-hr format while on the x-axis it is in 24-hr format. It should be consistent.

Screenshot 2022-03-23 at 3 28 40 PM

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #892

Demo: https://www.loom.com/share/87acb03a2e5e4b8c986ff3916fdc2480

### CODE REVIEW

File: frontend/src/components/Graph/index.tsx [hunk 1]
```diff
@@ -135,6 +136,10 @@ function Graph({
 					},
 					tooltip: {
 						callbacks: {
+							title(context) {
+								const date = new Date(context[0].parsed.x);
+								return format(date, 'MMM dd yyyy, HH:mm:ss');
```
Comment (palashgdev) [inline frontend/src/components/Graph/index.tsx:141]:
```suggestion
								return format(date, 'MMM dd yyyy, HH:mm:ss aaa');
```

**Review by palashgdev — CHANGES_REQUESTED** [review]

**Comment by palashgdev** [comment]
Hi @gitstart 
Thanks for sharing the PR can you please have a look in the suggested change after that it would be good to merge

File: frontend/src/components/Graph/index.tsx (hunk 1 above)
Comment (gitstart) [reply frontend/src/components/Graph/index.tsx:141]: Hi @palashgdev! Thank you for the review.
Happy to make the change but wouldn't it be redundant to use am or pm in 24h time format?

Comment (palashgdev) [reply frontend/src/components/Graph/index.tsx:141]: then can we make 12 h format ?

Comment (gitstart) [reply frontend/src/components/Graph/index.tsx:141]: Do you mean to convert the x-axis time format to 12h format instead? Sure, we can.

Comment (palashgdev) [reply frontend/src/components/Graph/index.tsx:141]: yup it would be great

File: frontend/src/components/Graph/index.tsx [hunk 2]
```diff
@@ -189,10 +189,10 @@ function Graph({
...
 							stepSize: xAxisTimeUnit?.stepSize || 1,
 							displayFormats: {
-								millisecond: 'HH:mm:ss',
-								second: 'HH:mm:ss',
-								minute: 'HH:mm',
-								hour: 'MM/dd HH:mm',
+								millisecond: 'hh:mm:ss aaa',
+								second: 'hh:mm:ss aaa',
+								minute: 'hh:mm aaa',
+								hour: 'MM/dd hh:mm aaaaa',
```
Comment (gitstart) [inline frontend/src/components/Graph/index.tsx:195]: using shorter notation for `hour` to prevent overlapping of texts
Screenshot 2023-01-17 at 9 29 41 PM

**Comment by gitstart** [comment]
Hi @palashgdev, PR has been updated please take a look

File: frontend/src/components/Graph/index.tsx (hunk 2 above)
Comment (srikanthccv) [reply frontend/src/components/Graph/index.tsx:196]: I would find it easier to read a 24-hour format both on the x-axis and on the chart. The am/pm doesn't look good to me.

**Comment by srikanthccv** [comment]
Look at this for example https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

**Comment by gitstart** [comment]
Hi @srikanthccv! Just want to confirm before pushing changes, does this work for you?
https://www.loom.com/share/8fc2c79c18244ac48a51370dee910720

**Review by palashgdev — APPROVED** [review]

**Comment by palashgdev** [comment]
Thanks @gitstart and sorry for the confusion :-D
