### PR TITLE
fix: autcomplete top level keys

### LINKED ISSUE #3078: [Logs] Autocomplete suggestions not working for top level keys
Autocomplete suggestions not working for top level  keys like trace_id, severity_text etc.

### PR DESCRIPTION
**Pull request by nityanandagohain**
We directly query the column for top level keys, but it was not working since there was a wrong codition, have fixed it.

Fixes #3078

### CODE REVIEW

File: pkg/query-service/app/clickhouseReader/reader.go [hunk 1]
```diff
@@ -3958,7 +3958,10 @@ func (r *ClickHouseReader) GetLogAttributeValues(ctx context.Context, req *v3.Fi
 
 	// if dataType or tagType is not present return empty response
 	if len(req.FilterAttributeKeyDataType) == 0 || len(req.TagType) == 0 || req.FilterAttributeKey == "body" {
-		return &v3.FilterAttributeValueResponse{}, nil
+		// also check if it is not a top level key
+		if _, ok := constants.StaticFieldsLogsV3[req.FilterAttributeKey]; !ok {
+			return &v3.FilterAttributeValueResponse{}, nil
+		}
```
Comment (srikanthccv) [inline pkg/query-service/app/clickhouseReader/reader.go:3964]: This LGTM, but I would expect the static fields to have the dataType and the tagType set. Isn't that the case?

**Review by srikanthccv — APPROVED** [review]
