### PR TITLE
fix: support in operator for json search 

### LINKED ISSUE #6441: Logs Explorer: JSON search for IN operator is not working
## Bug description

*Please describe.*  
In logs explorer search filter whenever I try to query for multiple values for an attribute inside the body json, the search doesn't work and it shows, the below text.

Aw snap :/ Something went wrong. Please try again or contact support.
Contact Support

## Expected behaviour
It should ideally show all logs based on the filters.

## How to reproduce

1. Got to logs explorer
2. In search filter query in body like: body.<someattribute> IN value1, value2
3. The search will break

## Version information 
* **Signoz version**: 0.58.0

#### *Thank you* for your bug report – we love squashing them!
Screenshot 2024-11-14 at 2 01 57 PM

[Reference Thread](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1731573125504539?thread_ts=1731391679.001799&cid=C01HWQ1R0BC)

### PR DESCRIPTION
**Pull request by nityanandagohain**
Fixes #6441 

----

> [!IMPORTANT]
> Adds support for `IN` and `NOT_IN` operators in JSON filters, with tests for various data types.
> 
>   - **Behavior**:
>     - Support for `IN` and `NOT_IN` operators in JSON filters added in `jsonFilterEnrich()` in `enrich_query.go`.
>     - Determines data type from the first element of the array for JSON filters.
>   - **Tests**:
>     - Added test cases for `IN` and `NOT_IN` operators in `enrich_query_test.go` and `json_filter_test.go`.
>     - Tests cover string, number, and mixed data types in arrays.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for ee402a15f9b4e1bae10cc4cf547899c2c8f20adf. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by nityanandagohain** [comment]
The ValidateAndCastValue function will try to cast the value to the dataType received for the first element. If there are mixed types and the first one is not the type of actual data present in the DB then the result will be empty, no errors though

**Comment by nityanandagohain** [comment]
Bump for review

File: pkg/query-service/app/logs/v3/enrich_query.go [hunk 1]
```diff
@@ -167,6 +167,24 @@ func jsonFilterEnrich(filter v3.FilterItem) v3.FilterItem {
...
+			case float32, float64:
+				valueType = "float64"
+			case bool:
+				valueType = "bool"
+			default:
+				valueType = "string"
+			}
+		} else {
+			valueType = "string"
+		}
```
Comment (srikanthccv) [inline pkg/query-service/app/logs/v3/enrich_query.go:187]: When does this happen? Does it create a valid query in this case?

File: pkg/query-service/app/logs/v4/json_filter_test.go [hunk 2]
```diff
@@ -183,6 +183,19 @@ var testGetJSONFilterData = []struct {
 		},
 		Filter: "lower(body) like lower('%message%') AND JSON_EXISTS(body, '$.\"message\"')",
 	},
+	{
+		Name: "exists",
```
Comment (srikanthccv) [inline pkg/query-service/app/logs/v4/json_filter_test.go:187]: s/exists/test json in/g

File: pkg/query-service/app/logs/v4/json_filter_test.go [hunk 3]
```diff
@@ -183,6 +183,19 @@ var testGetJSONFilterData = []struct {
...
+				Key:      "body.name",
+				DataType: "string",
+				IsJSON:   true,
+			},
+			Operator: "in",
+			Value:    []interface{}{"hello", "world"},
+		},
+		Filter: "lower(body) like lower('%name%') AND JSON_EXISTS(body, '$.\"name\"') AND JSON_VALUE(body, '$.\"name\"') IN ['hello','world']",
+	},
 }
```
Comment (srikanthccv) [inline pkg/query-service/app/logs/v4/json_filter_test.go:199]: Can you add a couple of more tests with other data types?

Comment (nityanandagohain) [reply pkg/query-service/app/logs/v4/json_filter_test.go:251]: have added more tests

File: pkg/query-service/app/logs/v3/enrich_query.go (hunk 1 above)
Comment (nityanandagohain) [reply pkg/query-service/app/logs/v3/enrich_query.go]: yeah, this won't happen. removed the else clause

**Review by srikanthccv — APPROVED** [review]
