### PR TITLE
fix: exclude internal attributes from promQL results

### LINKED ISSUE #8189: Exclude private internal attributes from the result in promql queries
Labels that start with `__` are private and provide no value to user. Exclude them from the result.

### PR DESCRIPTION
**Pull request by namanv3**
## Pull Request

---

### 📄 Summary

Currently, internal attributes like `__name__`, or `fingerprint` are shown in dashboards built using promql query. These need to be removed as they are not useful for the user in any way. 

#### Screenshots / Screen Recordings (if applicable)

Screenshot 2026-03-02 at 08 53 28

#### Issues closed by this PR

Closes #8189 

---

### ✅ Change Type
_Select all that apply_

- [ ] ✨ Feature
- [ ] 🐛 Bug fix
- [ ] ♻️ Refactor
- [ ] 🛠️ Infra / Tooling
- [ ] 🧪 Test-only

---

### 🐛 Bug Context

For dashboards built using promQL, users see internal keys like __scope.name__ which they shouldn't see

Screenshot 2026-03-02 at 08 56 21

### CODE REVIEW

**Comment by srikanthccv** [comment]
The change looks good, just unsure if people are relying on the returned data and have anything built around based on internal attributes.

File: pkg/querier/promql_query.go [hunk 1]
```diff
@@ -242,6 +242,9 @@ func (q *promqlQuery) Execute(ctx context.Context) (*qbv5.Result, error) {
 		var s qbv5.TimeSeries
 		lbls := make([]*qbv5.Label, 0, len(v.Metric))
 		for name, value := range v.Metric.Copy().Map() {
+			if strings.HasPrefix(name, "__") || name == "fingerprint" {
+				continue
+			}
```
Comment (srikanthccv) [inline pkg/querier/promql_query.go]: Let's make an exception for `__name__` and include it. The rest of them and `fingerprint`, drop it.

Comment (namanv3) [reply pkg/querier/promql_query.go]: Is this cuz you think `__name__` may be useful enough for people to do something with? I'll add it back.
Also how about we add some UI flag to include or exclude internal fields in the results? If after this change goes in and we get a bug saying that they need some internal flag, we can add the toggle

Comment (srikanthccv) [reply pkg/querier/promql_query.go]: > Is this cuz you think __name__ may be useful enough for people to do something with?

Yes

> Also how about we add some UI flag to include or exclude internal fields in the results? If after this change goes in and we get a bug saying that they need some internal flag, we can add the toggle

Every option on UI is tax to the most of the users that don't use it. It's not clear how they use other internal attributes. The remaining internal attributes are `__temporality__` and `__scope.***`. I can't think of any way how they can be useful. Let's rollout with just `__name__` and see how it goes.

Comment (namanv3) [reply pkg/querier/promql_query.go]: Yeah yeah, I'm assuming no user will actually complain about a missing internal label
