### PR TITLE
chore: fix filter editing issue in infra monitoring

### LINKED ISSUE #6884: Filter reset issue during edit mode

### PR DESCRIPTION
**Pull request by amlannandy**
### Summary

If a quick filters was already applied and we'd try to edit it later, the filter would get temporarily removed from the query and the list would be unfiltered. Fixed the issue here.

#### Related Issues / PR's

Fixes #6884

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

Infra Monitoring

----

> [!IMPORTANT]
> Fixes filter editing issue in `QueryBuilderSearch` for infra monitoring by managing editing state and conditionally triggering `onChange`.
> 
>   - **Behavior**:
>     - Fixes issue where editing a quick filter in infra monitoring temporarily removed it from the query.
>     - Introduces `isEditingTag` state in `QueryBuilderSearch` to track editing status.
>     - Modifies `onChange` logic to only trigger when editing is complete in infra monitoring mode.
>   - **Functions**:
>     - Adds `toggleEditMode` function to manage editing state transitions.
>     - Updates `onTagRender`, `onInputKeyDownHandler`, and `onBlur` to use `toggleEditMode` for managing edit state.
>   - **Misc**:
>     - Minor adjustments to `onChangeHandler` and `useEffect` for handling tag filters.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for e20652a20906ebe75690f04c9522cc928ba0cb3b. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx [hunk 1]
```diff
@@ -146,12 +158,16 @@ function QueryBuilderSearch({
...
+			// Editing is done after closing a tag
+			toggleEditMode(false);
 			handleSearch('');
 			setSearchKey('');
 		};
 
 		const tagEditHandler = (value: string): void => {
 			updateTag(value);
+			// Editing starts
+			toggleEditMode(true);
```
Comment (SagarRajput-7) [inline frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx:170]: please ensure no loose end is these, as in you are properly getting it toggle true and false

Comment (amlannandy) [reply frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx:170]: Yes. I did test it out and handled the scenarios. While editing the tag, there's 3 ways to exit editing and I did handled it there

**Review by SagarRajput-7 — APPROVED** [review]
