### PR TITLE
fix(FE/Logs): fix all logs not visible on scrolling

### LINKED ISSUE #3504: Incomplete logs visible in logs list view page
https://www.loom.com/share/9adfbb4ab5df4493a66270ac40ab2c44?sid=a3a91bf8-8437-4ef8-9e35-c157ac25c9ef

### PR DESCRIPTION
**Pull request by CKanishka**
Fixes #3504

https://github.com/SigNoz/signoz/assets/30779692/8aefd7c8-5248-46b5-b07f-eb3a778ba6f6

### CODE REVIEW

File: frontend/src/pages/Logs/index.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ function Logs(): JSX.Element {
 
 			<Row gutter={20} wrap={false}>
 				<LogsFilters />
-				<Col flex={1}>
+				<StyledCol flex={1}>
```
Comment (palashgdev) [inline frontend/src/pages/Logs/index.tsx:96]: scss

File: frontend/src/container/LogsTable/styles.ts [hunk 2]
```diff
@@ -15,3 +18,7 @@ export const Heading = styled(Card)`
 		padding: 0.3rem 0.5rem;
 	}
 `;
+
+export const LogsCard = styled(Card)`
```
Comment (palashgdev) [inline frontend/src/container/LogsTable/styles.ts:22]: same for this one

File: frontend/src/container/LogsTable/index.tsx [hunk 3]
```diff
@@ -85,13 +85,9 @@ function LogsTable(props: LogsTableProps): JSX.Element {
...
 
 		return (
-			<Card bodyStyle={contentStyle}>
-				<Virtuoso
-					useWindowScroll
-					totalCount={logs.length}
-					itemContent={getItemContent}
-				/>
-			</Card>
+			<LogsCard bodyStyle={{ ...contentStyle, height: '100%' }}>
```
Comment (palashgdev) [inline frontend/src/container/LogsTable/index.tsx:88]: can we use constant as we are using same style everywhere

**Review by palashgdev — APPROVED** [review]
LGTM
