### PR TITLE
fix(infra-monitoring): request loop when click to visualize volume

### LINKED ISSUE #8677: [Bug] Infrastructure > Volumes - PVC detail page causes infinite reload loop when clicked
## Bug description

Infrastructure > Volumes - PVC detail page causes infinite reload loop when clicked

When clicking on any PVC (Persistent Volume Claim) in the Infrastructure > Kubernetes > Volumes page, the detail page enters an infinite reload loop, making it impossible to view volume details. The page continuously
calls /api/v1/pvcs/list and /api/v1/event APIs hundreds of times within seconds.

Network Analysis:
- /api/v1/pvcs/list: Hundreds of calls per 10 seconds, ~50% return 200 OK, ~50% are (canceled)
- /api/v1/event: Hundreds of calls per 10 seconds, all return 200 OK
- This creates a race condition where new requests cancel previous ones

Screenshots: Network tab shows continuous API calls with many canceled requests

Image

Image

Image

https://github.com/user-attachments/assets/1e9a98e1-333a-4526-8205-2dc52b289610

## Expected behavior

Clicking on a PVC in the volumes list should open the volume detail page smoothly without infinite reloading, similar to how other Infrastructure pages (Pods, Nodes, Deployments) work normally.

## How to reproduce

1. Navigate to http://localhost:8080/infrastructure-monitoring/kubernetes?category=volumes
2. Wait for the volumes list to load (this works fine)
3. Click on any PVC in the list (e.g., nfs-test-pvc)
4. Observe that the page enters an infinite reload loop
5. Check browser Network tab to see hundreds of API calls being made continuously

## Version information 

- Signoz version: v0.91.0 (Helm Chart version 0.88.1)
- Browser version: Chrome 138.0.0 / Safari 537.36
- Your OS and version: macOS 10_15_7
- Your CPU Architecture(ARM/Intel): Intel

## Additional context

Environment:
- Kubernetes cluster with NFS StorageClass (nfs-client)
- Deployed via Helm with custom values
- PVC metrics are being collected properly by OpenTelemetry Collector

Troubleshooting attempts:
1. ✅ Other Infrastructure menus work fine: Pods, Nodes, Deployments, etc. have no issues
2. ✅ Volumes list page works: Can see all PVCs in the list view
3. ✅ Upgraded to v0.91.0: Issue persists after upgrade from v0.90.1
4. ✅ Browser cache cleared: Tried incognito mode, different browsers
5. ✅ Data cleanup: Deleted and re-collected PVC metrics, issue persists
6. ✅ PVC data verified: ClickHouse contains proper PVC metrics with correct metadata

Suspected Root Cause:
Based on source code analysis (K8sVolumesList.tsx), this appears to be a React useEffect dependency issue in the volume detail component, specifically related to the selectedVolumeData useMemo dependencies that trigger
infinite re-renders when a volume is selected.

Impact:
Currently impossible to view any PVC details in SigNoz Infrastructure monitoring, significantly limiting Kubernetes storage monitoring capabilities.

PVC data:
```
select * FROM signoz_metrics.time_series_v4 WHERE resource_attrs['k8s.persistentvolumeclaim.name'] = 'nfs-test-pvc';
```

```
INSERT INTO signoz_metrics.time_series_v4
(env, temporality, metric_name, description, unit, `type`, is_monotonic, fingerprint, unix_milli, labels, attrs, scope_attrs, resource_attrs, `__normalized`)
VALUES('dev', 'Unspecified', 'k8s.volume.available', 'The number of available bytes in the volume.', 'By', 'Gauge', false, 15987727545254462532, 1754006400000, '{"__name__":"k8s.volume.available","__scope.name__":"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver","__scope.schema_url__":"","__scope.version__":"0.109.0","__temporality__":"Unspecified","deployment.environment":"dev","host.name":"worker003","k8s.cluster.name":"flash-cluster-1","k8s.namespace.name":"observability","k8s.node.name":"worker003","k8s.node.uid":"3deb43f6-dc71-4161-92b0-50254ec519da","k8s.persistentvolumeclaim.name":"nfs-test-pvc","k8s.pod.name":"clean-test-pod-v2","k8s.pod.start_time":"2025-08-01T00:20:31Z","k8s.pod.uid":"812dd305-21a6-458e-9d03-81db34ac2d62","k8s.volume.name":"existing-nfs-storage","k8s.volume.type":"persistentVolumeClaim","os.type":"linux","signoz.component":"otel-agent"}', [{Key:__temporality__, Value:Unspecified}], [{Key:__scope.version__, Value:0.109.0}, {Key:__scope.schema_url__, Value:}, {Key:__scope.name__, Value:github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver}], [{Key:k8s.node.uid, Value:3deb43f6-dc71-4161-92b0-50254ec519da}, {Key:deployment.environment, Value:dev}, {Key:k8s.volume.name, Value:existing-nfs-storage}, {Key:k8s.pod.uid, Value:812dd305-21a6-458e-9d03-81db34ac2d62}, {Key:k8s.pod.name, Value:clean-test-pod-v2}, {Key:signoz.component, Value:otel-agent}, {Key:k8s.namespace.name, Value:observability}, {Key:k8s.volume.type, Value:persistentVolumeClaim}, {Key:k8s.cluster.name, Value:flash-cluster-1}, {Key:os.type, Value:linux}, {Key:k8s.pod.start_time, Value:2025-08-01T00:20:31Z}, {Key:k8s.node.name, Value:worker003}, {Key:k8s.persistentvolumeclaim.name, Value:nfs-test-pvc}, {Key:host.name, Value:worker003}], false);
INSERT INTO signoz_metrics.time_series_v4
(env, temporality, metric_name, description, unit, `type`, is_monotonic, fingerprint, unix_milli, labels, attrs, scope_attrs, resource_attrs, `__normalized`)
VALUES('dev', 'Unspecified', 'k8s.volume.capacity', 'The total capacity in bytes of the volume.', 'By', 'Gauge', false, 2090029449660887253, 1754006400000, '{"__name__":"k8s.volume.capacity","__scope.name__":"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver","__scope.schema_url__":"","__scope.version__":"0.109.0","__temporality__":"Unspecified","deployment.environment":"dev","host.name":"worker003","k8s.cluster.name":"flash-cluster-1","k8s.namespace.name":"observability","k8s.node.name":"worker003","k8s.node.uid":"3deb43f6-dc71-4161-92b0-50254ec519da","k8s.persistentvolumeclaim.name":"nfs-test-pvc","k8s.pod.name":"clean-test-pod-v2","k8s.pod.start_time":"2025-08-01T00:20:31Z","k8s.pod.uid":"812dd305-21a6-458e-9d03-81db34ac2d62","k8s.volume.name":"existing-nfs-storage","k8s.volume.type":"persistentVolumeClaim","os.type":"linux","signoz.component":"otel-agent"}', [{Key:__temporality__, Value:Unspecified}], [{Key:__scope.name__, Value:github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver}, {Key:__scope.version__, Value:0.109.0}, {Key:__scope.schema_url__, Value:}], [{Key:k8s.pod.uid, Value:812dd305-21a6-458e-9d03-81db34ac2d62}, {Key:k8s.persistentvolumeclaim.name, Value:nfs-test-pvc}, {Key:k8s.node.uid, Value:3deb43f6-dc71-4161-92b0-50254ec519da}, {Key:k8s.node.name, Value:worker003}, {Key:k8s.cluster.name, Value:flash-cluster-1}, {Key:k8s.volume.type, Value:persistentVolumeClaim}, {Key:os.type, Value:linux}, {Key:k8s.pod.name, Value:clean-test-pod-v2}, {Key:host.name, Value:worker003}, {Key:k8s.namespace.name, Value:observability}, {Key:k8s.volume.name, Value:existing-nfs-storage}, {Key:k8s.pod.start_time, Value:2025-08-01T00:20:31Z}, {Key:signoz.component, Value:otel-agent}, {Key:deployment.environment, Value:dev}], false);
INSERT INTO signoz_metrics.time_series_v4
(env, temporality, metric_name, description, unit, `type`, is_monotonic, fingerprint, unix_milli, labels, attrs, scope_attrs, resource_attrs, `__normalized`)
VALUES('dev', 'Unspecified', 'k8s.volume.inodes', 'The total inodes in the filesystem.', '1', 'Gauge', false, 455957351860863197, 1754006400000, '{"__name__":"k8s.volume.inodes","__scope.name__":"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver","__scope.schema_url__":"","__scope.version__":"0.109.0","__temporality__":"Unspecified","deployment.environment":"dev","host.name":"worker003","k8s.cluster.name":"flash-cluster-1","k8s.namespace.name":"observability","k8s.node.name":"worker003","k8s.node.uid":"3deb43f6-dc71-4161-92b0-50254ec519da","k8s.persistentvolumeclaim.name":"nfs-test-pvc","k8s.pod.name":"clean-test-pod-v2","k8s.pod.start_time":"2025-08-01T00:20:31Z","k8s.pod.uid":"812dd305-21a6-458e-9d03-81db34ac2d62","k8s.volume.name":"existing-nfs-storage","k8s.volume.type":"persistentVolumeClaim","os.type":"linux","signoz.component":"otel-agent"}', [{Key:__temporality__, Value:Unspecified}], [{Key:__scope.version__, Value:0.109.0}, {Key:__scope.schema_url__, Value:}, {Key:__scope.name__, Value:github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver}], [{Key:host.name, Value:worker003}, {Key:k8s.cluster.name, Value:flash-cluster-1}, {Key:k8s.namespace.name, Value:observability}, {Key:k8s.node.uid, Value:3deb43f6-dc71-4161-92b0-50254ec519da}, {Key:k8s.pod.name, Value:clean-test-pod-v2}, {Key:signoz.component, Value:otel-agent}, {Key:k8s.node.name, Value:worker003}, {Key:k8s.pod.uid, Value:812dd305-21a6-458e-9d03-81db34ac2d62}, {Key:k8s.volume.type, Value:persistentVolumeClaim}, {Key:deployment.environment, Value:dev}, {Key:k8s.pod.start_time, Value:2025-08-01T00:20:31Z}, {Key:k8s.volume.name, Value:existing-nfs-storage}, {Key:k8s.persistentvolumeclaim.name, Value:nfs-test-pvc}, {Key:os.type, Value:linux}], false);
INSERT INTO signoz_metrics.time_series_v4
(env, temporality, metric_name, description, unit, `type`, is_monotonic, fingerprint, unix_milli, labels, attrs, scope_attrs, resource_attrs, `__normalized`)
VALUES('dev', 'Unspecified', 'k8s.volume.inodes.free', 'The free inodes in the filesystem.', '1', 'Gauge', false, 3498905333495592567, 1754006400000, '{"__name__":"k8s.volume.inodes.free","__scope.name__":"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver","__scope.schema_url__":"","__scope.version__":"0.109.0","__temporality__":"Unspecified","deployment.environment":"dev","host.name":"worker003","k8s.cluster.name":"flash-cluster-1","k8s.namespace.name":"observability","k8s.node.name":"worker003","k8s.node.uid":"3deb43f6-dc71-4161-92b0-50254ec519da","k8s.persistentvolumeclaim.name":"nfs-test-pvc","k8s.pod.name":"clean-test-pod-v2","k8s.pod.start_time":"2025-08-01T00:20:31Z","k8s.pod.uid":"812dd305-21a6-458e-9d03-81db34ac2d62","k8s.volume.name":"existing-nfs-storage","k8s.volume.type":"persistentVolumeClaim","os.type":"linux","signoz.component":"otel-agent"}', [{Key:__temporality__, Value:Unspecified}], [{Key:__scope.schema_url__, Value:}, {Key:__scope.name__, Value:github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver}, {Key:__scope.version__, Value:0.109.0}], [{Key:k8s.persistentvolumeclaim.name, Value:nfs-test-pvc}, {Key:deployment.environment, Value:dev}, {Key:signoz.component, Value:otel-agent}, {Key:k8s.cluster.name, Value:flash-cluster-1}, {Key:k8s.volume.type, Value:persistentVolumeClaim}, {Key:k8s.pod.uid, Value:812dd305-21a6-458e-9d03-81db34ac2d62}, {Key:k8s.pod.start_time, Value:2025-08-01T00:20:31Z}, {Key:k8s.node.uid, Value:3deb43f6-dc71-4161-92b0-50254ec519da}, {Key:host.name, Value:worker003}, {Key:k8s.volume.name, Value:existing-nfs-storage}, {Key:k8s.node.name, Value:worker003}, {Key:k8s.pod.name, Value:clean-test-pod-v2}, {Key:k8s.namespace.name, Value:observability}, {Key:os.type, Value:linux}], false);
INSERT INTO signoz_metrics.time_series_v4
(env, temporality, metric_name, description, unit, `type`, is_monotonic, fingerprint, unix_milli, labels, attrs, scope_attrs, resource_attrs, `__normalized`)
VALUES('dev', 'Unspecified', 'k8s.volume.inodes.used', 'The inodes used by the filesystem. This may not equal inodes - free because filesystem may share inodes with other filesystems.', '1', 'Gauge', false, 15752415349670531724, 1754006400000, '{"__name__":"k8s.volume.inodes.used","__scope.name__":"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver","__scope.schema_url__":"","__scope.version__":"0.109.0","__temporality__":"Unspecified","deployment.environment":"dev","host.name":"worker003","k8s.cluster.name":"flash-cluster-1","k8s.namespace.name":"observability","k8s.node.name":"worker003","k8s.node.uid":"3deb43f6-dc71-4161-92b0-50254ec519da","k8s.persistentvolumeclaim.name":"nfs-test-pvc","k8s.pod.name":"clean-test-pod-v2","k8s.pod.start_time":"2025-08-01T00:20:31Z","k8s.pod.uid":"812dd305-21a6-458e-9d03-81db34ac2d62","k8s.volume.name":"existing-nfs-storage","k8s.volume.type":"persistentVolumeClaim","os.type":"linux","signoz.component":"otel-agent"}', [{Key:__temporality__, Value:Unspecified}], [{Key:__scope.name__, Value:github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver}, {Key:__scope.version__, Value:0.109.0}, {Key:__scope.schema_url__, Value:}], [{Key:k8s.cluster.name, Value:flash-cluster-1}, {Key:deployment.environment, Value:dev}, {Key:os.type, Value:linux}, {Key:k8s.volume.name, Value:existing-nfs-storage}, {Key:k8s.node.name, Value:worker003}, {Key:k8s.pod.uid, Value:812dd305-21a6-458e-9d03-81db34ac2d62}, {Key:host.name, Value:worker003}, {Key:k8s.node.uid, Value:3deb43f6-dc71-4161-92b0-50254ec519da}, {Key:k8s.pod.start_time, Value:2025-08-01T00:20:31Z}, {Key:k8s.volume.type, Value:persistentVolumeClaim}, {Key:k8s.persistentvolumeclaim.name, Value:nfs-test-pvc}, {Key:k8s.pod.name, Value:clean-test-pod-v2}, {Key:signoz.component, Value:otel-agent}, {Key:k8s.namespace.name, Value:observability}], false);
```

### PR DESCRIPTION
**Pull request by H4ad**
## Pull Request

This PR fixes the loop bug on select volumes caused by the min/max time being updates being included in the query to fetch data for the volume details charts.

---

This PR fixes the bug by not adding the min/max time into the query keys.

Before:

https://github.com/user-attachments/assets/9a8d5300-ccbf-4277-b071-b474c480e34b

After:

https://github.com/user-attachments/assets/375686d8-9fdc-4bad-864f-56e61a10bf50

Closes #8677

---

### ✅ Change Type
_Select all that apply_

- [ ] ✨ Feature
- [x] 🐛 Bug fix
- [ ] ♻️ Refactor
- [ ] 🛠️ Infra / Tooling
- [ ] 🧪 Test-only

---

The bug caused the page to enter in a loop of refetching the queries to get the volume data.

This was caused by min/max being updated for some reason after the queries for chart run.

Remove min/max from the query key.

---

- Tests added/updated: Yes
- Manual verification: Yes

---

| Field | Value |
|------|-------|
| Deployment Type | Cloud / OSS / Enterprise |
| Change Type | Bug Fix |
| Description | Fixed the loop bug when opening volumes inside Infrastructure Monitoring |

---

### 📋 Checklist
- [x] Tests added or explicitly not required
- [x] Manually tested
- [ ] Breaking changes documented
- [ ] Backward compatibility considered

### CODE REVIEW

File: frontend/src/container/InfraMonitoringK8s/Volumes/utils.tsx [hunk 1]
```diff
@@ -78,6 +78,70 @@ export const getK8sVolumesListQuery = (): K8sVolumesListPayload => ({
...
+	}
+	return [
+		'volumeList',
+		JSON.stringify(queryFilters),
+		JSON.stringify(orderBy),
+		JSON.stringify(groupBy),
+		selectedRowDataKey,
+		String(minTime),
+		String(maxTime),
+	];
```
[the remark this answers is not in the document]
Comment (H4ad) [reply frontend/src/container/InfraMonitoringK8s/Volumes/utils.tsx:109]: This causes loop error.

File: frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+					maxTime: Date.now() * 1000000,
+					selectedTime: '30m',
+				},
+			} as any);
+		});
+
+		// Allow any potential re-fetch to settle
+		await new Promise((resolve) => {
+			setTimeout(resolve, 300);
+		});
```
[the remark this answers is not in the document]
Comment (H4ad) [reply frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx:316]: This does not helps catch the regression or the bug if we introduce the same bug again.

File: frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx [hunk 3]
```diff
@@ -0,0 +1,285 @@
...
+								attributeKeys: [{ key: 'k8s_namespace_name', dataType: 'string' }],
+							},
+						}),
+					),
+			),
+		);
+
+		const { testStore } = renderWithRealStore(initialEntries);
+
+		await waitFor(() =>
```
Comment (AshwinBhatkal) [inline frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx]: findAllByText

File: frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx [hunk 4]
```diff
@@ -0,0 +1,285 @@
...
+			}),
+		);
+
+		const { testStore } = renderWithRealStore();
+
+		await waitFor(() => expect(apiCallCount).toBe(1));
+
+		const row = screen.getAllByText('test-pvc')[0].closest('tr');
+		fireEvent.click(row!);
+		await waitFor(() =>
```
Comment (AshwinBhatkal) [inline frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx]: here as well

File: frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx [hunk 5]
```diff
@@ -0,0 +1,285 @@
...
+		});
+
+		const row = screen.getAllByText('test-pvc')[0].closest('tr');
+		fireEvent.click(row!);
+
+		await waitFor(() => {
+			expect(screen.getByRole('button', { name: 'Close' })).toBeInTheDocument();
+		});
+
+		fireEvent.click(screen.getByRole('button', { name: 'Close' }));
```
Comment (AshwinBhatkal) [inline frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx]: userEvent

**Comment by AshwinBhatkal** [comment]
Good with changes. Reloading of table in the list upon click of list item to be picked up separately and fixed as it is a container level change across infra monitoring

File: frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx [hunk 6]
```diff
@@ -1,30 +1,103 @@
...
+	initialEntries?: string[],
+): { testStore: ReturnType<typeof createStore> } {
+	const testStore = createStore(reducers, applyMiddleware(thunk as any));
+	const queryClient = new QueryClient({
+		defaultOptions: { queries: { retry: false } },
+	});
+
+	render(
+		<QueryClientProvider client={queryClient}>
+			<Provider store={testStore}>
```
Comment (AshwinBhatkal) [inline frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/K8sVolumesList.test.tsx]: This Provider may not be required here

Similar to this PR https://github.com/SigNoz/signoz/pull/10640
