### PR TITLE
fix: export table panel

### LINKED ISSUE #3387: Export to dashboard from table view on logs/traces explorer doesn't export as table panel
The export to dashboard from table view of logs/traces explorer should export as table panel on dashboard

### PR DESCRIPTION
**Pull request by yeshev**
Close #3387

### CODE REVIEW

File: frontend/src/container/LogsExplorerViews/index.tsx [hunk 1]
```diff
@@ -334,9 +340,11 @@ function LogsExplorerViews(): JSX.Element {
 
 					const dashboardEditView = `${generatePath(ROUTES.DASHBOARD, {
 						dashboardId: data?.payload?.uuid,
-					})}/new?${QueryParams.graphType}=graph&${QueryParams.widgetId}=empty&${
-						queryParamNamesMap.compositeQuery
-					}=${encodeURIComponent(JSON.stringify(exportDefaultQuery))}`;
+					})}/new?${QueryParams.graphType}=${panelTypeParam}&${
```
Comment (palashgdev) [inline frontend/src/container/LogsExplorerViews/index.tsx:343]: can we have common handler though in future we would adding another explorer page which would be good to handle from one single source of truth

**Review by palashgdev — APPROVED** [review]

**Comment by srikanthccv** [comment]
@YounixM please review it. It would be good to get this merged for release.

**Review by makeavish — APPROVED** [review]

**Comment by makeavish** [comment]
> @YounixM please review it. It would be good to get this merged for release.

Merging this as this was reviewed by @palashgdev, I have functionally tested this as well.
